### ISSUE TITLE
Enemies spawns through LevelChoreographer won't get destroyed if they end up below the screen.

### ISSUE THREAD

**Issue by kyle-flynn** [kyle-flynn/Space-Journey#3]
The enemies are currently being spawned correctly, but if they aren't killed by the player, they keep living throughout the game life cycle. They are not disposed or checked in any way.

Might need to attach some sort of update listener to each ChoreographEvent, and check if the entity is out of bounds. 

Would this cause a performance impact?
Is this worth it in the long run?

**Comment by JohnDoneth** [comment]
Entities are now removed from the Ashley ECS Engine if they are outside of a specified bounding box and have a Enemy component or a Projectile component. The enemy component is simply a dumb object for tagging entities for now, for use with problems such as this, as it contains no members.
